### ISSUE TITLE
Question on recovery and training data

### ISSUE THREAD

**Issue by Qubitium** [horseee/LLM-Pruner#1]
Excellent project btw and I am sure it will get traction.

I am curious about the recovery stage. Is the team proposing recovery training using the same training data that created the base model?

**Comment by horseee** [comment]
Hi. 
We didn't use the training data from the base model as the cost of acquiring and training the model on that data is too high. For our experiments, we used the alpaca dataset (cleaned version). The code for the recovery phase will be released within the next two days-v-

**Comment by ysanimals** [comment]
when I use alpaca data for post-training, I find loss is becoming bigger and bigger, what's wrong with it?
