### ISSUE TITLE
Zero-shot Evaluation

### ISSUE THREAD

**Issue by Duncan1115** [horseee/LLM-Pruner#10]
Hi, thanks for your great work!
I wonder how to evaluate the pruned and fintuned model in lm-evaluation-harness?

**Comment by horseee** [comment]
Hi.
We release the code, and you can now follow the [instructions](https://github.com/horseee/LLM-Pruner#4-evaluation) to run the evaluation😄
We haven't comprehensively tested whether the current evaluation code works well on different devices and on different version of PyTorch, so if you find any problem, feel free to ask me!

**Comment by Duncan1115** [comment]
Thanks! It helps me a lot.
