### ISSUE TITLE
Code for evaluation on zero-shot tasks using lm-evaluation-harness

### ISSUE THREAD

**Issue by jameslahm** [horseee/LLM-Pruner#14]
Thank you for your great work! Since the pruned model cannot be loaded with the .from_pretrained() in Hugging Face, would you mind sharing the code for evaluation on zero-shot tasks using lm-evaluation-harness? Thanks a lot!

**Comment by horseee** [comment]
Hi. 
We release the code, and you can now follow the [instructions](https://github.com/horseee/LLM-Pruner#4-evaluation) to run the evaluation😄
We haven't comprehensively tested whether the current evaluation code works well on different devices and on different version of PyTorch, so if you find any problem, feel free to ask me!

**Comment by jameslahm** [comment]
Thanks a lot!
