### ISSUE TITLE
Error occurs when pruning LLaMa2-7b

### ISSUE THREAD

**Issue by moonlightian** [horseee/LLM-Pruner#22]
With cmd like:
CUDA_VISIBLE_DEVICES=0 python hf_prune.py --base_model path_to_cached_hf_llama2-7b --pruning_ratio 0.25 --device cpu  --eval_device cuda --block_wise --block_mlp_layer_start 4 --block_mlp_layer_end 30 --block_attention_layer_start 4 --block_attention_layer_end 30 --pruner_type taylor --test_after_train --taylor param_first --save_model
It throws an error :"addmm_impl_cpu_" not implemented for 'Half'
![image](https://github.com/horseee/LLM-Pruner/assets/49636631/42a43843-abf1-4d04-8faf-939cc2cbc6be)

torch==2.0.0
transformers==4.31.0

**Comment by moonlightian** [comment]
remove --device cpu ,solved
while it still failed with an shape error
![image](https://github.com/horseee/LLM-Pruner/assets/49636631/58f8e4d9-e87c-41c3-9198-2998ad9888ef)

**Comment by horseee** [comment]
Hi. Do you modify the code for loading the Llama2?

**Comment by moonlightian** [comment]
> Hi. Do you modify the code for loading the Llama2?

Yes， I modified the code loading the model from
`    # tokenizer = LlamaTokenizer.from_pretrained(args.base_model)
    # model = LlamaForCausalLM.from_pretrained(
    #     args.base_model,
    #     low_cpu_mem_usage=True if args.torch_version >=1.9 else False
    # )`
to
`    from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig
    model_path = args.base_model
    config = AutoConfig.from_pretrained(model_path, trust_remote_code=True)
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False, trust_remote_code=True)
    kwargs = {"torch_dtype": torch.float16, "low_cpu_mem_usage": True}
    model = AutoModelForCausalLM.from_pretrained(
        model_path, config=config, trust_remote_code=True, **kwargs)`
Because I found it unsuccessful to load models with oringin codes

**Comment by horseee** [comment]
Ahh..The model code for llama2 needs to be modified to satisfy the updated attribute. Some of the dimension calculation is fixed in the official code, which is unsuitable for the inference of the pruned model.

Two ways to solve this bug:
1. Modify the fixed attribute in the modeling_llama.py. The problematic attribute is the self.num_key_value_heads, and you can manually set it (below is an example):
```
for layer in model.model.layers:
      layer.self_attn.num_heads = layer.self_attn.q_proj.weight.data.shape[0] // layer.self_attn.head_dim
```

2. Use the code in this repo to load the model. I'm not sure why it is unsuccessful to load the model. If possible, could you plot the error msg here?

**Comment by moonlightian** [comment]
> 

Thank you for your kind advice! It worked finally.

**Comment by owlsan49** [comment]
if you use --device cpu and --save_model, in below fragment of code, the model will be turned into half precise. So you got the first error.
![image](https://github.com/horseee/LLM-Pruner/assets/54353918/68cb5cc6-8b55-4385-bb45-de18a5b8ad03)

You just need to add 'model.float()' behind 'torch.save' like this, and you will solve the first error.
![image](https://github.com/horseee/LLM-Pruner/assets/54353918/a8a32376-79c4-40af-8f56-c79e3e221301)
