### ISSUE TITLE
Evaluation metric (acc vs. acc_norm) for lm-evaluation-harness tasks

### ISSUE THREAD

**Issue by bokyeong1015** [horseee/LLM-Pruner#25]
Hi, thank you very much for generously open-sourcing your excellent work.

I've run [the evaluation code you kindly shared](https://github.com/horseee/LLM-Pruner/tree/aa05f422788506f9642a97aa2cc51615cb7cd771#4-evaluation) and obtained the below results. I have a question regarding the metric for each task. Could you please clarify which one between `acc` or `acc_norm` [[ref](https://blog.eleuther.ai/multiple-choice-normalization/)] was used for the PIQA, HellaSwag, ARC-e, ARC-c, and OBQA tasks? Thanks for taking the time to check this inquiry.

#### 20%-pruned -> post-trained LLaMA from [scripts/llama_prune.sh](https://github.com/horseee/LLM-Pruner/blob/aa05f422788506f9642a97aa2cc51615cb7cd771/scripts/llama_prune.sh)

- Reproduced with [LLM-Pruner's code](https://github.com/horseee/LLM-Pruner/tree/aa05f422788506f9642a97aa2cc51615cb7cd771#4-evaluation) based on [lm-evaluation-harness 4d21ab6b27](https://github.com/EleutherAI/lm-evaluation-harness/tree/4d21ab6b2713cc3a8b4fa7574e89c62ef504e75f)

| Task | BoolQ | PIQA  | HellaSwag | WinoGrande | ARC-e | ARC-c | OBQA |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| LLM-Pruner paper | 66.79 | 77.58 | 68.48 | 64.96 | 64.06 | 37.88 | 39.00 |
| Reproduced: `acc` | <ins>65.20</ins> | <ins>77.15<ins> | 53.19 | <ins>63.69<ins> | <ins>64.77<ins> | 36.26 | 28.80 |
| Reproduced: `acc_norm` | n/a | 76.93 | <ins>68.63<ins> | n/a | 52.27 | <ins>36.95<ins> | <ins>40.40<ins> |

#### Original LLaMA-7B

- Reproduced with [LLM-Pruner's code](https://github.com/horseee/LLM-Pruner/tree/aa05f422788506f9642a97aa2cc51615cb7cd771#4-evaluation) based on [lm-evaluation-harness 4d21ab6b27](https://github.com/EleutherAI/lm-evaluation-harness/tree/4d21ab6b2713cc3a8b4fa7574e89c62ef504e75f)

| Task | BoolQ | PIQA  | HellaSwag | WinoGrande | ARC-e | ARC-c | OBQA |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| LLaMA paper | 76.5 | 79.8 | 76.1 | 70.1 | 72.8 | 47.6 | 57.2 |
| LLM-Pruner paper | 73.18 | 78.35 | 72.99 | 67.01 | 67.45 | 41.38 | 42.40 |
| Reproduced (LLM-Pruner code): `acc` | <ins>73.06</ins> | <ins>78.35</ins> | 56.42 | <ins>67.01</ins> | <ins>67.34</ins> | 38.14 | 28.20 |
| Reproduced (LLM-Pruner): `acc_norm` | n/a | 77.37 | <ins>72.99</ins> | n/a | 52.48 | <ins>41.38</ins> | <ins>42.40</ins> |

- Reproduced* with **different** commit hash, [lm-evaluation-harness 3326c547a7](https://github.com/EleutherAI/lm-evaluation-harness/tree/3326c547a733d598b4377e54be96e194861b964c)

| Task | BoolQ | PIQA  | HellaSwag | WinoGrande | ARC-e | ARC-c | OBQA |
|---|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| Reproduced* (Different hash): `acc` | <ins>75.05</ins> | <ins>78.67</ins> | 56.93 | <ins>69.93</ins> | <ins>75.29</ins> | 41.89 | 34.60 |
| Reproduced* (Different): `acc_norm` | n/a | 79.16 | <ins>76.22</ins> | n/a | 72.85 | <ins>44.71</ins> | <ins>44.40</ins> |

#### Note
- <ins>underline score</ins>: reported metrics in the LLM-Pruner paper
- The scores reported in LLM-Pruner paper are **fully reproducible using this repo**, and the lm-evaluation-harness version affects the scores because of recent updates.
- [Table 1 of LLM-Pruner Paper] The evaluation is performed under different prompts, which is lower than the official results in the LLaMA paper.

**Comment by horseee** [comment]
Hi. I used these keys: 
select_key = {
    'boolq': 'acc',
    'hellaswag': 'acc_norm',
    'arc_easy': 'acc',
    'piqa': 'acc',
    'arc_challenge': 'acc_norm',
    'winogrande': 'acc',
    'openbookqa': 'acc_norm',
}

Besides, I saw the difference in the performance of the original LLaMA-7B. I double-checked the code and used the evaluation code in my repo to re-evaluate the performance of LLaMA-7B, and I got a very similar performance (on ARC-easy, 67.38 vs. 67.45). Does the performance of LLaMA-7B you listed above use the lm-evaluation-harness ([a previous commit of lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness/tree/4d21ab6b2713cc3a8b4fa7574e89c62ef504e75f)) in my repo? Since the lm-evaluation-harness has changed a lot in these months, some results are not consistent.

**Comment by bokyeong1015** [comment]
Thank you for your response and clarification!

I apologize for the missing commit hash regarding the LLaMA-7B results. Upon your indication, I realized that I used a different hash for lm-evaluation-harness compared to your code.

---

> Since the lm-evaluation-harness has changed a lot in these months, some results are not consistent.

Thanks for pointing out this point. To ensure clarity, I've updated the table above and will soon provide results using your evaluation code. Thanks again for your assistance.

**Comment by bokyeong1015** [comment]
Hi, I've added the results using your repo, which are fully reproducible. I also made an explicit note to avoid any confusion. Big thanks for your time and help!

> Note
> 
> - <ins>underline score</ins>: reported metrics in the LLM-Pruner paper
> - The scores reported in LLM-Pruner paper are fully reproducible using this repo, and the lm-evaluation-harness version affects the scores because of recent updates.
> - [Table 1 of LLM-Pruner Paper] The evaluation is performed under different prompts, which is lower than the official results in the LLaMA paper.

**Comment by horseee** [comment]
Hi😄 . Thank you very much for the detailed notes and the experimental results you contributed based on the new version of the lm-evaluation-harness!
