### ISSUE TITLE
Latency code

### ISSUE THREAD

**Issue by tuidan** [horseee/LLM-Pruner#33]
Can you share your latency code in the experiment? In my test on A100, I found that the pruned LLaMA-7b is even slower than original LLaMA. Thank you very much!

**Comment by horseee** [comment]
Hi. You need to increase the batch_size to make the GPU utilization reaches around 100%. Since the pruned model is not deliberately designed towards a hardware-friendly architecture (e.g., some special number for dimension), using a small batch_size may not have an effect on speedup the model.

**Comment by Arnav0400** [comment]
Can you please provide the exact script for calculating the latency, we want to compare your work with one of our research project!
