### ISSUE TITLE
延迟评估

### ISSUE THREAD

**Issue by qxpBlog** [horseee/LLM-Pruner#50]
您在论文中提到的延迟数据具体是运行那个文件得到的：
![image](https://github.com/horseee/LLM-Pruner/assets/96739096/81ca509f-97f0-477c-8732-5eaf1a1378dd)

**Comment by qxpBlog** [comment]
@VainF @eltociear @horseee

**Comment by BrownTan** [comment]
Why you closed it? I also want to know

**Comment by qxpBlog** [comment]
> Why you closed it? I also want to know

Maybe is the ```test_speedup.py``` file. I just use ```time.time()``` to record the latency.

**Comment by BrownTan** [comment]
thank you

> > Why you closed it? I also want to know
> 
> Maybe is the `test_speedup.py` file. I just use `time.time()` to record the latency.
